data:
  obj_dir: data/ground_truth_img/SIM-generating_image.tiff
  probe_dir: data/ground_truth_img/SIM-generating_probe.tiff
  data_dir: data/synthetic_noisy_data/probe_spacing_20/photon_rate_100000.0/
  init_guess_form: formulated                                             # formulated or ground truth
  window_coords: [112, 912, 112, 912]
  display: False
recon:
  num_iter: 100
ePIE:
  obj_step_sz: 1
  out_dir: ePIE/
WF:
  out_dir: WF/
AWF:
  out_dir: AWF/
SHARP:
  relax_pm: 0.6
  out_dir: SHARP/
SHARP_plus:
  relax_pm: 0.9
  out_dir: SHARP_plus/
PMACE:
  alpha: 1
  rho: 0.5
  probe_exponent: 1.25
  out_dir: PMACE/
reg-PMACE:
  alpha: 0.5
  rho: 0.5
  probe_exponent: 1.25
  reg_wgt: 0.6
  noise_std: 15/255
  prior: bm3d
  out_dir: reg-PMACE/
output:
  out_dir: output/

