data:
  obj_dir: data/synthetic_noisy_data/ground_truth_img/SIM-generating_image.tiff
  probe_dir: data/synthetic_noisy_data/ground_truth_img/SIM-generating_probe.tiff
  data_dir: data/synthetic_noisy_data/probe_spacing_20/photon_rate_10000.0/
  window_coords: [112, 912, 112, 912]
  display: True
recon:
  num_iter: 100
ePIE:
  obj_step_sz: 1
  probe_step_sz: 1
  out_dir: ePIE/
WF:
  out_dir: WF/
AWF:
  out_dir: AWF/
SHARP:
  relax_pm: 0.6
  out_dir: SHARP/
SHARP_plus:
  relax_pm: 0.6
  out_dir: SHARP_plus/
PMACE:
  obj_noisetosignal_ratio: 0.5
  probe_noisetosignal_ratio: 1
  rho: 0.5
  probe_exponent: 1.5
  obj_exponent: 0.5
  out_dir: PMACE/
reg-PMACE:
  obj_noisetosignal_ratio: 0.5
  probe_noisetosignal_ratio: 1
  rho: 0.5
  probe_exp: 1.5
  obj_exp: 0.5
  reg_wgt: 0.6
  noise_std: 5/255
  prior_model: bm3d
  out_dir: reg-PMACE/
output:
  out_dir: output/joint_recon/

