data:
  obj_dir: data/ground_truth_img/realIC/SIM-generating_object.tiff
  probe_dir: data/ground_truth_img/realIC/SIM-generating_probe.tiff
  data_dir: data/synthetic_data/noisy_data/probe_spacing_20/photon_rate_100000.0/
  init_obj_form: formulated                                                # formulated / ground truth
  init_probe_form: formulated                                              # formulated  ground truth
  window_coords: [150, 511, 150, 511]
  display: True
recon:
  num_iter: 10
ePIE:
  obj_step_sz: 1
  probe_step_sz: 1
  out_dir: ePIE/
WF:
  out_dir: WF/
AWF:
  out_dir: AWF/
SHARP:
  relax_pm: 0.4
  out_dir: SHARP/
SHARP_plus:
  relax_pm: 0.44
  out_dir: SHARP_plus/
PMACE:
  obj_noisetosignal_ratio: 0.5
  probe_noisetosignal_ratio: 1
  rho: 0.5
  probe_exponent: 1.25
  obj_exponent: 0.25
  out_dir: PMACE/
reg-PMACE:
  obj_noisetosignal_ratio: 0.5
  probe_noisetosignal_ratio: 1
  rho: 0.5
  probe_exp: 1.25
  obj_exp: 0.25
  reg_wgt: 0.05
  noise_std: 20/255
  prior_model: bm3d
  out_dir: reg-PMACE/
output:
  out_dir: output/joint_recon/

