data:
  obj_dir: data/synthetic_noisy_data/ground_truth_img/SIM-generating_image.tiff
  probe_dir: data/synthetic_noisy_data/ground_truth_img/SIM-generating_probe.tiff
  data_dir: data/synthetic_noisy_data/probe_spacing_68/photon_rate_10000.0/
  window_coords: [112, 912, 112, 912]
  display: False
recon:
  num_iter: 100
ePIE:
  obj_step_sz: 1
  probe_step_sz: 1
  out_dir: ePIE/
WF:
  out_dir: WF/
AWF:
  out_dir: AWF/
SHARP:
  relax_prm: 0.6
  out_dir: SHARP/
SHARP_plus:
  relax_prm: 0.8
  out_dir: SHARP_plus/
PMACE:
  obj_prm: 0.5
  probe_prm: 0.5
  probe_exp: 1.5
  obj_exp: 0.5
  out_dir: PMACE/
reg-PMACE:
  obj_prm: 0.5
  probe_prm: 1
  probe_exp: 1.5
  obj_exp: 0.5
  bm3d_psd: 0.01
  out_dir: reg-PMACE/
output:
  out_dir: output/demo_joint_recon_output/

