dataset:
  download_url: https://engineering.purdue.edu/~bouman/data_repository/data/PMACE_demo_data.tgz
  save_dir: ../data/
data:
  obj_dir: synthetic_data/SyntheticImg_data/ground_truth_img/SIM-generating_image.tiff
  probe_dir: synthetic_data/SyntheticImg_data/ground_truth_img/SIM-generating_probe.tiff
  data_dir: synthetic_data/SyntheticImg_data/simulated_data/photon_peak_1e4/probe_dist_68/
  window_coords: [112, 912, 112, 912]
recon:
  num_iter: 100
  joint_recon: False
  out_dir: ../output/demo_pmace_result/
  data_fit_param: 0.7
  rho: 0.5
  probe_exp: 1.5
  denoising_param: 0.02