data:
  obj_dir: ../data/PMACE_demo_data/synthetic_data/SyntheticImg_data/ground_truth_img/SIM-generating_image.tiff
  probe_dir: ../data/PMACE_demo_data/synthetic_data/SyntheticImg_data/ground_truth_img/SIM-generating_probe.tiff
  num_meas: 64
  probe_spacing: 100
  max_scan_loc_offset: 5
  add_noise: True
  peak_photon_rate: 1e4
  shot_noise_rate: 0.5
  data_dir: ../data/synthetic_data/SyntheticImg_data/simulated_data/
  display: False


