data:
  obj_dir: ../data/synthetic_noisy_data/ground_truth_img/SIM-generating_image.tiff
  probe_dir: ../data/synthetic_noisy_data/ground_truth_img/SIM-generating_probe.tiff
  data_dir: ../data/synthetic_noisy_data/probe_spacing_68/photon_rate_10000.0/
  window_coords: [112, 912, 112, 912]
recon:
  num_iter: 100
  joint_recon: False
  out_dir: ../output/demo_pmace_result/
  data_fit_param: 0.7
  rho: 0.5
  probe_exp: 1.5
  denoising_param: 0.02